### ISSUE TITLE
Asteroid tracker

### ISSUE THREAD

**Issue by joesingo** [joesingo/tom_education#10]
Replacing the existing Asteroid tracker website:
* Website: https://asteroidtracker.lco.global/
* Code: https://github.com/LCOGT/asteroidtracker

Will be a simple website that
* Lists a subset of targets from a TOM (education) instance
* Shows info about them
* Shows timelapses
* Allows observations to be submitted, and emails received on status change

Workflow:
* Asteroid admin sets up TOM education instance
* Creates targets. Adds extra field `html_info` to each, and add `html_info` in `EXTRA_FIELDS` in `settings.py`
* Creates observation template for each
* Generates static Asteroid Tracker site

Changes to `tom_education`:
- [x] Ensure HTML info extra field is not shown in sidebar in target detail view
- [x] Optionally store email addresses with observations
- [x] Cron job to:
    * Go through targets
    * Go through observations for target
    * If completed, download data. Mark target as needing timelapse update. If email address attached to obs, send an update email
    * After going through obs, create timelapse of all DPs for target
    * Optionally delete old timelapses (controlled by flag in `settings.py`)
- [x] ~~Target list API endpoint:~~
- [x] Target detail API endpoint:
    * Give PK
    * Get extra fields
    * URLs for timelapses
- [x] Submit observation API endpoint:
    * Not authenticated, but try to prevent abuse (look into DRF [throttling](https://www.django-rest-framework.org/api-guide/throttling/))
    * Parameters are: target PK, email address, start and end dates, observation template

Asteroid Tracker:
* Home page: list targets and basic info (name)
* Detail page for target:
    * `info` attribute
    * Most recent timelapse
    * Submission form: fields for email address, start and end dates
 * Consider a completely static site, with everything done in JS via Ajax

**Comment by joesingo** [comment]
Future:
- [ ] Include all non-FITS data products in target detail API response, not just timelapses

**Comment by joesingo** [comment]
## Notes:
* ~~Does not have distinction of an asteroid being 'active' as the old site does~~ (no longer true)
